name: CI

on:
    push:
        branches: [main]
    pull_request: {}

jobs:
    test:
        name: Node.js v${{ matrix.nodejs }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [10, 12, 14]
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: ${{ matrix.nodejs }}

            - run: echo "::add-path::$(yarn global bin)"

            - name: Install
              run: |-
                  yarn --frozen-lockfile;
                  yarn global add nyc;

            - name: Compile
              run: yarn build

            - name: Test
              run: nyc --include=src yarn test
